# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-677501-ece-lnx-10/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcu250-figd2104-2L-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /ecel/UFAD/miguel.sanchez1/BNN_actual/openflex/rtl/bnn_fcc_timing.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Arg_MAX.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/bnn_fcc.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BNN_Hidden.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BNN_Layer_NoStallInput.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BNN_Layer_StallableInput.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BNN_OutputLayer_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BRAM_LUT_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BRAM_LUT_SINK.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/BRAM_SINK.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Build_W.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Byte_Index.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Config_HiddenLayer_Control.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Config_Manager.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Config_OutputLayer_Control.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Delay_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Delay_FF_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Delay2_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Delay3_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/fanout_tree_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/fanout_tree.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/FIFO.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Input_Buffer_NoStall.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Input_Buffer_Stallable.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Input_Layer_Unit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Input_Layer.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Layer_Control_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Layer_Control_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_MEM_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_MEM_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_Pop_unit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_Threshold_Unit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_UNIT_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_UNIT_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_XNOR_unit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Pulse_Delay.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Pulse.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Register_ALWAYS.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Register.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Skid_Buffer.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/StickyBit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Layer_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_Layer_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_FSM_WithOutputValid.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_DP_WithThreshold.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_Accum_Unit.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/Layer_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_Layer_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_FSM_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/NP_DP_PopcountOnly.sv
      /ecel/UFAD/miguel.sanchez1/BNN_actual/rtl/Used/Not_Divided/bnn_output_fifo.sv
    }
      rt::read_verilog -sv /apps/reconfig/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_vhdl -lib xpm /apps/reconfig/tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-677501-ece-lnx-10/realtime/bnn_fcc_timing_synth.xdc
    rt::sdcChecksum
    set rt::top bnn_fcc_timing
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-677501-ece-lnx-10/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -param {
  { INPUT_DATA_WIDTH 8 }
  { INPUT_BUS_WIDTH 64 }
  { CONFIG_BUS_WIDTH 64 }
  { OUTPUT_DATA_WIDTH 4 }
  { OUTPUT_BUS_WIDTH 8 }
  { TOTAL_LAYERS 4 }
} -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
